CREATE DATABASE IF NOT EXISTS bookstore_customer;
CREATE DATABASE IF NOT EXISTS bookstore_order;
CREATE DATABASE IF NOT EXISTS bookstore_pay;
CREATE DATABASE IF NOT EXISTS bookstore_ship;
CREATE DATABASE IF NOT EXISTS bookstore_staff;
CREATE DATABASE IF NOT EXISTS bookstore_manager;
